# push-pull 에서 오류 해결

일반적으로, 작업이 끝나고 `push`,  작업시작전에 `pull` 을 통해서 원격 저장소 내용을 업데이트 하면 문제가 발생하지 않는다.



다만, 서로 다른 이력으로 구성되는 경우 push 를 하려고 하면  아래의 메세지가 뜬다

```bash

```